apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: HEAD
    path: apps/demo-service/helm
  helm:
    parameters:
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
